### PR TITLE
resolve #1 by setting up unit tests in the standard extension way

### LINKED ISSUE #1: Tests not working
For some reason the test stopped successfully installing the extensions. FN getKeysToContainer is only returning root keys. This was working & stopped which makes me think I muffed up some syntax somewhere.... @totten .... help

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by seamuslee001** [comment]
\test

**Comment by seamuslee001** [comment]
so tests aren't running not helpful but this I found worked for me @eileenmcnaughton works for you?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I probably would rather just take your word on this one than jump in and test to confirm

**Pull request merged**
