### PR TITLE
Fix issues where multiple extensions were defining on the same entity

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @ineffyble

**Comment by eileenmcnaughton** [comment]
I'm sold

**Comment by jitendrapurohit** [comment]
@seamuslee001 Can you explain why this is required and what issue it fixes? As we are intentionally taking the first value of the setting, this change does not load both the options defined on https://github.com/eileenmcnaughton/nz.co.fuzion.relatedpermissions/blob/master/settings/related_permissions.entity_setting.php on the relationship edit form.

**Comment by seamuslee001** [comment]
@jitendrapurohit Jitendra the issue was that we had 2 different extensions providing entity settings for the same entity in this case contribution_pages and it was only the 2nd extensions values.

**Comment by eileenmcnaughton** [comment]
As an aside - I had some conversation about upstreaming this extension  - I feel the resolution was that we should make all entities custom-field extendable (at the api level, not necessarily form) and use custom fields

**Pull request merged**
